#!/bin/bash
alias ssh="TERM=xterm-256color ssh"
alias gp="git push -o ci.skip"
alias gpu="git push -o ci.skip --set-upstream origin"
alias gb="git checkout -b"
alias free='free -m'                      # show sizes in MB
alias vi="nvim"
alias hg="history | grep"
alias pg="ps -ef | grep"
alias cd="z"
alias tmuxs="tmux -S /var/tmux/shared-session"
function server()
{
    TERM=xterm-256color ssh roetsm@$1
}
